version: '2'
services:
  first-object:
    container_name: first_container
    build:
      dockerfile: Dockerfile
    image: springio/gs-spring-boot-docker
    ports:
      - "8080:8080"
  second_object:
    container_name: second_container
    build:
      dockerfile: Dockerfile
    image: springio/gs-spring-boot-docker
    ports:
      - "8081:8080"