kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: calculator
  labels:
    app: calculator-app
spec:
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: "https://github.com/jericho1798/calculator.git"
      ref: master
  output:
    to:
      kind: ImageStreamTag
      name: calculator:latest