kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: calculator
  labels:
    app: calculator-app
spec:
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      securityContext:
      containers:
        - name: calculator
          image: vsb1798/calculator-docker:latest
